import type { NextPage } from 'next';
import Head from 'next/head';
import Upload from '@pages/Upload';
const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Upload />
        </div>
    );
};
export default Home;
